# Generated by Django 5.0.4 on 2024-05-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_header",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Cabeçalho do site",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Título do site",
                    ),
                ),
                (
                    "index_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Título da página principal",
                    ),
                ),
                (
                    "welcome_msg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de boas vindas"
                    ),
                ),
                (
                    "goodbye_msg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de despedida"
                    ),
                ),
                (
                    "administration_header",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Cabeçalho da administração do site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do site",
            },
        ),
    ]
