# Generated by Django 5.0.4 on 2024-05-20 17:07

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_configuration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfiguration",
            name="port",
            field=models.PositiveIntegerField(default=587, verbose_name="Porta"),
        ),
        migrations.AlterField(
            model_name="emailconfiguration",
            name="signature",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Assinatura dos emails"
            ),
        ),
    ]
