# Generated by Django 5.0.4 on 2024-05-22 17:06

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_configuration", "0002_alter_emailconfiguration_port_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfiguration",
            name="signature",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Para usar essa assinatura em seus emails, utilize a variável <code>{{ signature }}</code>.",
                null=True,
                verbose_name="Assinatura dos emails",
            ),
        ),
    ]
