# Generated by Django 5.0.4 on 2024-05-23 06:01

import datetime
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_configuration", "0004_emailconfiguration_from_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="ending_hour",
            field=models.TimeField(
                default=datetime.time(18, 0),
                verbose_name="Horário de fim de funcionamento",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="working_days",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (1, "Domingo"),
                    (2, "Segunda-feira"),
                    (3, "Terça-feira"),
                    (4, "Quarta-feira"),
                    (5, "Quinta-feira"),
                    (6, "Sexta-feira"),
                    (7, "Sábado"),
                ],
                default="2,3,4,5,6",
                max_length=13,
                verbose_name="Dias de funcionamento",
            ),
        ),
    ]
