# Generated by Django 5.0.4 on 2024-05-27 17:31

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_configuration", "0005_siteconfiguration_ending_hour_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="backup",
            name="db_or_media",
        ),
        migrations.RemoveField(
            model_name="backup",
            name="db_dump",
        ),
        migrations.RemoveField(
            model_name="backup",
            name="do_db_dump",
        ),
        migrations.RemoveField(
            model_name="backup",
            name="do_media_dump",
        ),
        migrations.RemoveField(
            model_name="backup",
            name="media_dump",
        ),
        migrations.AddField(
            model_name="backup",
            name="dump",
            field=models.FileField(
                blank=True,
                upload_to=pathlib.PurePosixPath("backups"),
                verbose_name="Arquivo de backup",
            ),
        ),
        migrations.AddField(
            model_name="backup",
            name="status",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=256,
                verbose_name="Status do processamento",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="name",
            field=models.CharField(blank=True, max_length=127, verbose_name="Nome"),
        ),
    ]
