# Generated by Django 5.0.4 on 2024-05-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="grade",
        ),
        migrations.AddField(
            model_name="profile",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Número de registro"
            ),
        ),
    ]
