-include dev/makefile.variables

serverdo=[ -n $(host) ] && ssh $(host)
environ=set -a; . .env; set +a
manage=$(environ); $(venv); ./manage.py

deploy_pull:
	$(serverdo) 'cd $(folder); git pull --rebase'

deploy_pip:
	$(serverdo) 'cd $(folder); $(environ); $(venv); pip install -r requirements.txt'

deploy_migrate:
	$(serverdo) 'cd $(folder); $(manage) migrate'

deploy_static:
	$(serverdo) 'cd $(folder); $(manage) collectstatic --noinput'

deploy_restart:
	$(serverdo) 'systemctl restart apache2'

backup_condition=git diff HEAD HEAD~1 --name-only | grep -q migrations
deploy_backup:
	$(serverdo) 'cd $(folder); if $(backup_condition); then $(manage) backup; fi'


deploy_huey:
	@[ -f "$(huey_service)" ] || { \
		echo "Não encontrei deploy/huey.service. Abortando..." && false ; \
	}
	scp $(huey_service) $(host):/etc/systemd/system/huey.service


deploy_enable_huey:
	$(serverdo) 'systemctl enable huey'

deploy_restart_huey:
	$(serverdo) 'systemctl restart huey'

huey_service=deploy/huey.service
deploy_configuration: deploy_huey deploy_enable_huey deploy_restart_huey

deploy: deploy_pull deploy_pip deploy_migrate deploy_static \
	deploy_restart deploy_backup deploy_restart_huey
