# Generated by Django 5.0.4 on 2024-04-29 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import books.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Nome por extenso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classificação",
                "verbose_name_plural": "Classificações",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Nome",
                    ),
                ),
            ],
            options={
                "verbose_name": "Localização",
                "verbose_name_plural": "Localizações",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "isbn",
                    models.CharField(
                        max_length=13,
                        primary_key=True,
                        serialize=False,
                        validators=[books.validators.validate_isbn],
                        verbose_name="ISBN",
                    ),
                ),
                ("title", models.TextField(verbose_name="Título")),
                (
                    "author_first_names",
                    models.CharField(
                        max_length=100,
                        verbose_name="Primeiros nomes do autor",
                    ),
                ),
                (
                    "author_last_name",
                    models.CharField(
                        max_length=50, verbose_name="Último nome do autor"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(max_length=300, verbose_name="Editora"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, verbose_name="Código"),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.classification",
                        verbose_name="Classificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
            },
        ),
        migrations.AddField(
            model_name="classification",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.location",
                verbose_name="Localização",
            ),
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Número",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimens",
                        to="books.book",
                        verbose_name="Livro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exemplar",
                "verbose_name_plural": "Exemplares",
            },
        ),
        migrations.AddConstraint(
            model_name="specimen",
            constraint=models.UniqueConstraint(
                fields=("number", "book"), name="unique specimen number"
            ),
        ),
    ]
