# Generated by Django 5.0.4 on 2024-05-04 22:57

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                max_length=13,
                null=True,
                validators=[books.validators.validate_isbn],
                verbose_name="ISBN",
            ),
        ),
    ]
