# Generated by Django 5.0.4 on 2024-05-16 17:12

import books.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_author_first_names_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="É o padrão?"),
                ),
                (
                    "name",
                    models.CharField(
                        default="Acervo regular", max_length=128, verbose_name="Nome"
                    ),
                ),
            ],
            options={
                "verbose_name": "Acervo",
                "verbose_name_plural": "Acervos",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="collection",
            field=models.ForeignKey(
                default=books.models.Collection.get_default_pk,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="books.collection",
                verbose_name="Acervo",
            ),
        ),
    ]
