# Generated by Django 5.0.4 on 2024-05-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_remove_book_unique_isbn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="code",
            field=models.CharField(
                editable=False, max_length=50, verbose_name="Código cutter"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Editora"
            ),
        ),
    ]
