# Generated by Django 5.0.4 on 2024-05-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_collection_book_collection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["name"],
                "verbose_name": "Acervo",
                "verbose_name_plural": "Acervos",
            },
        ),
    ]
