# Generated by Django 5.0.4 on 2024-05-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_book_options_alter_specimen_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_collection_name"
            ),
        ),
    ]
