# Generated by Django 5.0.4 on 2024-05-28 15:16

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_specimen_label_printed"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="book",
            name="unique_isbn",
        ),
        migrations.RemoveConstraint(
            model_name="book",
            name="unique_code",
        ),
        migrations.AlterField(
            model_name="book",
            name="code",
            field=models.CharField(
                editable=False,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Código cutter",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[books.validators.validate_isbn],
                verbose_name="ISBN",
            ),
        ),
    ]
