# Generated by Django 5.0.4 on 2024-05-13 02:21

import django.db.models.deletion
import labels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("labels", "0001_initial"),
        ("labels", "0002_labelpageconfiguration_paper_size"),
        ("labels", "0003_remove_labelpageconfiguration_box_w_and_more"),
        ("labels", "0004_rename_n_label_labelpageconfiguration_n_cols_and_more"),
        ("labels", "0005_alter_labelpageconfiguration_n_cols_and_more"),
        ("labels", "0006_labelpageconfiguration_include_barcode_and_more"),
        ("labels", "0007_remove_labelpageconfiguration_include_barcode_and_more"),
        (
            "labels",
            "0008_rename_info_font_size_labelpageconfiguration_info_size_and_more",
        ),
        ("labels", "0009_rename_info_size_labelpageconfiguration_font_size"),
        ("labels", "0010_labelprint_use_isbn"),
    ]

    initial = True

    dependencies = [
        ("books", "0002_location_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelPageConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=127, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "margin_top",
                    models.FloatField(default=8, verbose_name="Margem superior"),
                ),
                (
                    "margin_bottom",
                    models.FloatField(default=8.5, verbose_name="Margem inferior"),
                ),
                (
                    "horizontal_gap",
                    models.FloatField(default=2.5, verbose_name="Separação horizontal"),
                ),
                (
                    "vertical_gap",
                    models.FloatField(default=0, verbose_name="Separação vertical"),
                ),
                (
                    "font_size",
                    models.FloatField(
                        default=8, verbose_name="Tamanho da fonte de informações"
                    ),
                ),
                (
                    "paper_size",
                    models.CharField(
                        default="a4",
                        help_text="Use dois números separados por vírgula, representando a largura e altura em milímetros, ou um dos seguintes: a4, a3, a5, letter ou legal",
                        max_length=10,
                        validators=[labels.models.validate_page_size],
                        verbose_name="Tamanho da página",
                    ),
                ),
                (
                    "margin_left",
                    models.FloatField(default=6.5, verbose_name="Marge esquerda"),
                ),
                (
                    "margin_right",
                    models.FloatField(default=6.5, verbose_name="Margem direita"),
                ),
                (
                    "n_cols",
                    models.IntegerField(default=3, verbose_name="Número de colunas"),
                ),
                (
                    "n_rows",
                    models.IntegerField(default=11, verbose_name="Número de linhas"),
                ),
            ],
            options={
                "verbose_name": "Configuração de página",
                "verbose_name_plural": "Configurações de página",
            },
        ),
        migrations.CreateModel(
            name="LabelPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127, verbose_name="Nome")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "labels_file",
                    models.FileField(
                        upload_to="labels", verbose_name="Arquivo com as etiquetas"
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labels.labelpageconfiguration",
                        verbose_name="Configuração",
                    ),
                ),
                (
                    "specimens",
                    models.ManyToManyField(
                        editable=False,
                        related_name="label_prints",
                        to="books.specimen",
                        verbose_name="Exemplares",
                    ),
                ),
                (
                    "include_barcode",
                    models.BooleanField(
                        default=False, verbose_name="Incluir código de barras"
                    ),
                ),
                (
                    "use_border",
                    models.BooleanField(default=False, verbose_name="Usar borda"),
                ),
                (
                    "use_color",
                    models.BooleanField(default=False, verbose_name="Usar cor"),
                ),
                (
                    "use_isbn",
                    models.BooleanField(
                        default=False,
                        help_text="Só válido se o campo acima estiver ativado",
                        verbose_name="Usar ISBN no código de barras",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de etiquetas",
                "verbose_name_plural": "Etiquetas",
            },
        ),
    ]
