# Generated by Django 5.0.4 on 2024-05-16 03:38

import django.db.models.deletion
import labels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelPageConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=127, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "paper_size",
                    models.CharField(
                        default="a4",
                        help_text="Use dois números separados por vírgula, representando a largura e altura em milímetros, ou um dos seguintes: a4, a3, a5, letter ou legal",
                        max_length=10,
                        validators=[labels.models.validate_page_size],
                        verbose_name="Tamanho da página",
                    ),
                ),
                (
                    "n_rows",
                    models.IntegerField(default=11, verbose_name="Número de linhas"),
                ),
                (
                    "n_cols",
                    models.IntegerField(default=3, verbose_name="Número de colunas"),
                ),
                (
                    "margin_top",
                    models.FloatField(default=8, verbose_name="Margem superior"),
                ),
                (
                    "margin_bottom",
                    models.FloatField(default=8.5, verbose_name="Margem inferior"),
                ),
                (
                    "margin_left",
                    models.FloatField(default=6.5, verbose_name="Marge esquerda"),
                ),
                (
                    "margin_right",
                    models.FloatField(default=6.5, verbose_name="Margem direita"),
                ),
                (
                    "horizontal_gap",
                    models.FloatField(default=2.5, verbose_name="Separação horizontal"),
                ),
                (
                    "vertical_gap",
                    models.FloatField(default=0, verbose_name="Separação vertical"),
                ),
                (
                    "font_size",
                    models.FloatField(
                        default=8, verbose_name="Tamanho da fonte de informações"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de página",
                "verbose_name_plural": "Configurações de página",
            },
        ),
        migrations.CreateModel(
            name="LabelPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=labels.models.label_name,
                        max_length=127,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "labels_file",
                    models.FileField(
                        upload_to="labels", verbose_name="Arquivo com as etiquetas"
                    ),
                ),
                (
                    "use_color",
                    models.BooleanField(default=False, verbose_name="Usar cor"),
                ),
                (
                    "use_border",
                    models.BooleanField(default=False, verbose_name="Usar borda"),
                ),
                (
                    "include_barcode",
                    models.BooleanField(
                        default=False, verbose_name="Incluir código de barras"
                    ),
                ),
                (
                    "use_isbn",
                    models.BooleanField(
                        default=False,
                        help_text="Caso contrário, usa o identificador único do exemplar. Só válido se o campo acima estiver ativado.",
                        verbose_name="Usar ISBN no código de barras",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labels.labelpageconfiguration",
                        verbose_name="Configuração",
                    ),
                ),
                (
                    "specimens",
                    models.ManyToManyField(
                        editable=False,
                        related_name="label_prints",
                        to="books.specimen",
                        verbose_name="Exemplares",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de etiquetas",
                "verbose_name_plural": "Etiquetas",
            },
        ),
    ]
