# Generated by Django 5.0.4 on 2024-05-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelpageconfiguration",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="É o padrão?"),
        ),
    ]
