# Generated by Django 5.0.4 on 2024-05-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0003_remove_labelprint_include_barcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelprint",
            name="include_marked",
            field=models.BooleanField(
                default=False,
                verbose_name="Incluir exemplares com marcação de etiqueta impressa",
            ),
        ),
        migrations.AddField(
            model_name="labelprint",
            name="mark_labeled",
            field=models.BooleanField(
                default=True,
                verbose_name="Fazer marcação de etiqueta impressa nos exemplares",
            ),
        ),
    ]
