# Generated by Django 5.0.4 on 2024-05-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0004_labelprint_include_marked_labelprint_mark_labeled"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelprint",
            name="status",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=512,
                verbose_name="Status do processamento",
            ),
        ),
        migrations.AlterField(
            model_name="labelprint",
            name="labels_file",
            field=models.FileField(
                upload_to="labels", verbose_name="Arquivo com as etiquetas"
            ),
        ),
    ]
