# Generated by Django 5.0.4 on 2024-05-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="renewal",
            options={
                "ordering": ["order"],
                "verbose_name": "Renovação",
                "verbose_name_plural": "Renovações",
            },
        ),
        migrations.AddField(
            model_name="renewal",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordem"
            ),
        ),
    ]
