# Generated by Django 5.0.4 on 2024-05-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="triggers",
        ),
        migrations.AddField(
            model_name="notification",
            name="trigger",
            field=models.IntegerField(
                choices=[
                    (1, "Expira em <n> dias"),
                    (2, "Atrasado há <n> dias"),
                    (3, "Atrasado a cada <n> dias"),
                    (4, "Recibo de empréstimo"),
                ],
                default=4,
                verbose_name="tipo de gatilho",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Trigger",
        ),
    ]
