# Generated by Django 5.0.4 on 2024-05-22 21:27

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_remove_notification_triggers_notification_trigger_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=tinymce.models.HTMLField(
                help_text="Variáveis disponíveis: <code>{{ author }}, {{ book }}, {{ due }}, {{ late_days }}, {{ loan_date }}, {{ name }}, {{ return_date }}, {{ signature }}, {{ site_title }}</code>",
                verbose_name="Mensagem",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="n_parameter",
            field=models.IntegerField(
                blank=True,
                help_text="Só é utilizado se o tipo de gatilho contiver '<n>'",
                null=True,
                validators=[django.core.validators.MinValueValidator],
                verbose_name="Parâmetro <n>",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="trigger",
            field=models.IntegerField(
                choices=[
                    (1, "Expira em <n> dias"),
                    (2, "Atrasado há <n> dias"),
                    (3, "Atrasado a cada <n> dias"),
                    (4, "Recibo de empréstimo"),
                    (5, "Recibo de devolução"),
                    (6, "Recibo de renovação"),
                ],
                verbose_name="tipo de gatilho",
            ),
        ),
    ]
